In [1]:
# Import pandas library and load the Excel dataset into a DataFrame
import pandas as pd
df = pd.read_csv(r'C:\Users\ashok\Data_Analytics_Projects\Developer Burnout & Workplace Stress Analytics\indian_developer_burnout_2026.csv')

In [2]:
# To preview or display the first 5 rows of the dataset
df.head()

,Developer Id,Age,Gender,City,State,Marital Status,Education Level,Company Type,Company Size,Job Role,...,Layoff anxiety score,Ai replacement fear score,Job security confidence,Emergency savings months,Linkedin job search activity,Applied jobs last 30 days,Burnout risk category,Likely to switch job,Mentally exhausted,High layoff risk
0,DEV00001,31,Male,Hyderabad,Telangana,Single,M.Tech,Freelance,01-Oct,Backend Developer,...,5.1,4.8,7.2,3.0,Low,4,High,No,Yes,No
1,DEV00002,27,Male,Bengaluru,Karnataka,Single,B.Tech,Product-based,201-1000,DevOps Engineer,...,1.8,5.5,10.0,8.0,NaN,4,Low,No,No,No
2,DEV00003,31,Male,Delhi,Delhi,Married,B.Tech,Startup,Nov-50,Frontend Developer,...,5.2,3.3,5.9,7.0,Low,4,High,Maybe,Yes,No
3,DEV00004,36,Male,Pune,Maharashtra,Single,MCA,Freelance,01-Oct,Android Developer,...,5.2,7.0,8.1,2.0,Very High,6,High,Yes,Yes,No
4,DEV00005,27,Male,Pune,Maharashtra,Single,B.Tech,Service-based,5000+,Data Scientist,...,4.5,6.6,8.0,2.0,Very High,4,Medium,No,Yes,No

In [3]:
# To display dataset structure, column names, data types, and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 50 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Developer Id                        5000 non-null   object
 1   Age                                 5000 non-null   int64
 2   Gender                              5000 non-null   object
 3   City                                5000 non-null   object
 4   State                               5000 non-null   object
 5   Marital Status                      5000 non-null   object
 6   Education Level                     5000 non-null   object
 7   Company Type                        5000 non-null   object
 8   Company Size                        5000 non-null   object
 9   Job Role                            5000 non-null   object
 10  Employment Type                     5000 non-null   object
 11  Experience Years                    5000 non-null   float64
 12  Salary Lpa                          5000 non-null   float64
 13  Years in current company            5000 non-null   float64
 14  Promotion last 2 years              5000 non-null   object
 15  Remote work ratio                   5000 non-null   int64
 16  Weekly work hours                   5000 non-null   float64
 17  Weekend work frequency              5000 non-null   object
 18  Night shift frequency               5000 non-null   object
 19  Layoffs seen in company             5000 non-null   object
 20  Number of switches                  5000 non-null   int64
 21  Primary language                    5000 non-null   object
 22  Tech stack                          5000 non-null   object
 23  Ai tools usage hours per week       5000 non-null   float64
 24  Upskilling hours per week           4875 non-null   float64
 25  Leetcode problems solved            4875 non-null   float64
 26  Certifications count                4875 non-null   float64
 27  Side projects count                 4875 non-null   float64
 28  Github activity score               4875 non-null   float64
 29  Interview preparation hours weekly  4875 non-null   float64
 30  Stress level                        5000 non-null   float64
 31  Burnout score                       5000 non-null   float64
 32  Anxiety score                       5000 non-null   float64
 33  Sleep hours                         5000 non-null   float64
 34  Caffeine intake per day             4875 non-null   float64
 35  Work life balance rating            5000 non-null   float64
 36  Imposter syndrome score             5000 non-null   float64
 37  Social media usage hours            4875 non-null   float64
 38  Physical activity days per week     5000 non-null   int64
 39  Therapy or counseling               4875 non-null   object
 40  Layoff anxiety score                5000 non-null   float64
 41  Ai replacement fear score           5000 non-null   float64
 42  Job security confidence             5000 non-null   float64
 43  Emergency savings months            4875 non-null   float64
 44  Linkedin job search activity        4091 non-null   object
 45  Applied jobs last 30 days           5000 non-null   int64
 46  Burnout risk category               5000 non-null   object
 47  Likely to switch job                5000 non-null   object
 48  Mentally exhausted                  5000 non-null   object
 49  High layoff risk                    5000 non-null   object
dtypes: float64(23), int64(5), object(22)
memory usage: 1.9+ MB

In [4]:
# To check the summary statistics for numeric columns in DataFrame.
df.describe()

,Age,Experience Years,Salary Lpa,Years in current company,Remote work ratio,Weekly work hours,Number of switches,Ai tools usage hours per week,Upskilling hours per week,Leetcode problems solved,...,Caffeine intake per day,Work life balance rating,Imposter syndrome score,Social media usage hours,Physical activity days per week,Layoff anxiety score,Ai replacement fear score,Job security confidence,Emergency savings months,Applied jobs last 30 days
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,4875.000000,4875.000000,...,4875.000000,5000.000000,5000.00000,4875.000000,5000.000000,5000.00000,5000.000000,5000.000000,4875.000000,5000.000000
mean,28.245200,5.418680,26.979186,1.927240,45.309800,48.115960,2.192800,5.13384,4.967836,134.717128,...,2.743590,6.877640,5.16682,2.869272,2.638600,4.25390,5.189700,7.222940,5.517538,4.620400
std,4.794213,4.369203,16.132555,1.527937,31.813026,10.033851,1.477858,4.65854,4.785292,123.670909,...,1.642649,1.630233,1.51496,2.133841,1.636253,1.51491,1.763183,1.379341,4.776525,2.843575
min,21.000000,0.500000,3.500000,0.100000,0.000000,30.000000,0.000000,0.00000,0.000000,1.000000,...,0.000000,1.100000,1.00000,0.200000,0.000000,1.00000,1.000000,2.400000,1.000000,0.000000
25%,25.000000,2.300000,16.930000,0.800000,19.000000,41.200000,1.000000,1.90000,1.400000,48.000000,...,2.000000,5.800000,4.10000,1.200000,1.000000,3.20000,4.000000,6.300000,2.000000,3.000000
50%,28.000000,4.100000,23.935000,1.500000,42.000000,47.100000,2.000000,3.70000,3.500000,95.000000,...,3.000000,6.900000,5.20000,2.200000,3.000000,4.20000,5.100000,7.300000,4.000000,4.000000
75%,31.000000,7.300000,33.612500,2.500000,76.000000,53.400000,3.000000,6.90000,6.900000,183.000000,...,4.000000,8.000000,6.20000,3.900000,4.000000,5.30000,6.400000,8.200000,8.000000,6.000000
max,48.000000,28.000000,308.490000,19.500000,100.000000,94.900000,9.000000,30.00000,25.000000,1080.000000,...,9.000000,10.000000,10.00000,8.000000,7.000000,10.00000,10.000000,10.000000,36.000000,15.000000

In [5]:
# To display summary statistics for both numerical and categorical columns
df.describe(include = 'all')

,Developer Id,Age,Gender,City,State,Marital Status,Education Level,Company Type,Company Size,Job Role,...,Layoff anxiety score,Ai replacement fear score,Job security confidence,Emergency savings months,Linkedin job search activity,Applied jobs last 30 days,Burnout risk category,Likely to switch job,Mentally exhausted,High layoff risk
count,5000,5000.000000,5000,5000,5000,5000,5000,5000,5000,5000,...,5000.00000,5000.000000,5000.000000,4875.000000,4091,5000.000000,5000,5000,5000,5000
unique,5000,NaN,4,15,12,4,8,6,6,14,...,NaN,NaN,NaN,NaN,4,NaN,3,3,2,2
top,DEV00001,NaN,Male,Bengaluru,Maharashtra,Single,B.Tech,Service-based,1001-5000,Full Stack Developer,...,NaN,NaN,NaN,NaN,Medium,NaN,Low,No,No,No
freq,1,NaN,3408,1146,1206,2529,1838,1498,1089,833,...,NaN,NaN,NaN,NaN,1457,NaN,2983,3445,2945,4864
mean,NaN,28.245200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.25390,5.189700,7.222940,5.517538,NaN,4.620400,NaN,NaN,NaN,NaN
std,NaN,4.794213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.51491,1.763183,1.379341,4.776525,NaN,2.843575,NaN,NaN,NaN,NaN
min,NaN,21.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00000,1.000000,2.400000,1.000000,NaN,0.000000,NaN,NaN,NaN,NaN
25%,NaN,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.20000,4.000000,6.300000,2.000000,NaN,3.000000,NaN,NaN,NaN,NaN
50%,NaN,28.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.20000,5.100000,7.300000,4.000000,NaN,4.000000,NaN,NaN,NaN,NaN
75%,NaN,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.30000,6.400000,8.200000,8.000000,NaN,6.000000,NaN,NaN,NaN,NaN
max,NaN,48.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.00000,10.000000,10.000000,36.000000,NaN,15.000000,NaN,NaN,NaN,NaN

In [6]:
# To check the null values in table
df.isnull()

,Developer Id,Age,Gender,City,State,Marital Status,Education Level,Company Type,Company Size,Job Role,...,Layoff anxiety score,Ai replacement fear score,Job security confidence,Emergency savings months,Linkedin job search activity,Applied jobs last 30 days,Burnout risk category,Likely to switch job,Mentally exhausted,High layoff risk
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
# To get the count of null values per column
df.isnull().sum()

Developer Id                            0
Age                                     0
Gender                                  0
City                                    0
State                                   0
Marital Status                          0
Education Level                         0
Company Type                            0
Company Size                            0
Job Role                                0
Employment Type                         0
Experience Years                        0
Salary Lpa                              0
Years in current company                0
Promotion last 2 years                  0
Remote work ratio                       0
Weekly work hours                       0
Weekend work frequency                  0
Night shift frequency                   0
Layoffs seen in company                 0
Number of switches                      0
Primary language                        0
Tech stack                              0
Ai tools usage hours per week           0
Upskilling hours per week             125
Leetcode problems solved              125
Certifications count                  125
Side projects count                   125
Github activity score                 125
Interview preparation hours weekly    125
Stress level                            0
Burnout score                           0
Anxiety score                           0
Sleep hours                             0
Caffeine intake per day               125
Work life balance rating                0
Imposter syndrome score                 0
Social media usage hours              125
Physical activity days per week         0
Therapy or counseling                 125
Layoff anxiety score                    0
Ai replacement fear score               0
Job security confidence                 0
Emergency savings months              125
Linkedin job search activity          909
Applied jobs last 30 days               0
Burnout risk category                   0
Likely to switch job                    0
Mentally exhausted                      0
High layoff risk                        0
dtype: int64

In [8]:
# Numerical columns
num_cols = [ 
    'Upskilling hours per week',
    'Leetcode problems solved',
    'Certifications count',
    'Side projects count',
    'Github activity score',
    'Interview preparation hours weekly',
    'Caffeine intake per day',
    'Social media usage hours',
    'Emergency savings months'
]

In [9]:
#  Fill with median
for columns in num_cols: df[columns] = df[columns].fillna(df[columns].median())

In [10]:
# Categorical columns
cat_cols = [
    'Therapy or counseling',
    'Linkedin job search activity'
]

In [11]:
# Fill categorical nulls with mode
for columns in cat_cols: df[columns] = df[columns].fillna(df[columns].mode()[0])

In [12]:
# Check null values again
df.isnull().sum()

Developer Id                          0
Age                                   0
Gender                                0
City                                  0
State                                 0
Marital Status                        0
Education Level                       0
Company Type                          0
Company Size                          0
Job Role                              0
Employment Type                       0
Experience Years                      0
Salary Lpa                            0
Years in current company              0
Promotion last 2 years                0
Remote work ratio                     0
Weekly work hours                     0
Weekend work frequency                0
Night shift frequency                 0
Layoffs seen in company               0
Number of switches                    0
Primary language                      0
Tech stack                            0
Ai tools usage hours per week         0
Upskilling hours per week             0
Leetcode problems solved              0
Certifications count                  0
Side projects count                   0
Github activity score                 0
Interview preparation hours weekly    0
Stress level                          0
Burnout score                         0
Anxiety score                         0
Sleep hours                           0
Caffeine intake per day               0
Work life balance rating              0
Imposter syndrome score               0
Social media usage hours              0
Physical activity days per week       0
Therapy or counseling                 0
Layoff anxiety score                  0
Ai replacement fear score             0
Job security confidence               0
Emergency savings months              0
Linkedin job search activity          0
Applied jobs last 30 days             0
Burnout risk category                 0
Likely to switch job                  0
Mentally exhausted                    0
High layoff risk                      0
dtype: int64

In [13]:
# Convert column names to lowercase and replace spaces with underscores
df.columns = df.columns.str.lower().str.replace(' ','_')

In [14]:
df.columns

Index(['developer_id', 'age', 'gender', 'city', 'state', 'marital_status',
       'education_level', 'company_type', 'company_size', 'job_role',
       'employment_type', 'experience_years', 'salary_lpa',
       'years_in_current_company', 'promotion_last_2_years',
       'remote_work_ratio', 'weekly_work_hours', 'weekend_work_frequency',
       'night_shift_frequency', 'layoffs_seen_in_company',
       'number_of_switches', 'primary_language', 'tech_stack',
       'ai_tools_usage_hours_per_week', 'upskilling_hours_per_week',
       'leetcode_problems_solved', 'certifications_count',
       'side_projects_count', 'github_activity_score',
       'interview_preparation_hours_weekly', 'stress_level', 'burnout_score',
       'anxiety_score', 'sleep_hours', 'caffeine_intake_per_day',
       'work_life_balance_rating', 'imposter_syndrome_score',
       'social_media_usage_hours', 'physical_activity_days_per_week',
       'therapy_or_counseling', 'layoff_anxiety_score',
       'ai_replacement_fear_score', 'job_security_confidence',
       'emergency_savings_months', 'linkedin_job_search_activity',
       'applied_jobs_last_30_days', 'burnout_risk_category',
       'likely_to_switch_job', 'mentally_exhausted', 'high_layoff_risk'],
      dtype='object')

In [15]:
# Divide employees into experience groups
# create a column experience_group
num = [0, 2, 5, 10, 20, 30]
lables = ['Fresher', 'Early Career', 'Mid Level', 'Senior', 'Veteran']

In [16]:
# Categorize employees into experience-based segments to simplify analysis and modeling
df['experience_group'] = pd.cut(
    df['experience_years'],
    bins=[0, 2, 5, 10, 20, 30],
    labels=['Fresher', 'Early Career', 'Mid Level', 'Senior', 'Veteran']
)

In [17]:
df[['experience_years', 'experience_group']].head()

   experience_years experience_group
0               2.2     Early Career
1               3.5     Early Career
2              11.9           Senior
3               4.5     Early Career
4               3.4     Early Career

In [18]:
# Examine unique category values to detect inconsistencies in the company_size column
for val in df['company_size'].unique():
    print(repr(val))

'01-Oct'
'201-1000'
'Nov-50'
'5000+'
'51-200'
'1001-5000'

In [19]:
# Standardize company size categories by fixing Excel-induced date format conversions
df.loc[df['company_size'].str.contains('Oct', na=False), 'company_size'] = '1-10'
df.loc[df['company_size'].str.contains('Nov', na=False), 'company_size'] = '11-50'

In [20]:
for val in df['company_size'].unique():
    print(repr(val))

'1-10'
'201-1000'
'11-50'
'5000+'
'51-200'
'1001-5000'

In [21]:
# Installs psycopg2-binary for PostgreSQL connection and SQLAlchemy for database handling in Python
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\ashok\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\ashok\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\ashok\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ashok\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [22]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# connect to postgresql
username = "postgres"
password = quote_plus("123456789")
host = "localhost"
port = "5432"
database = "DEVELOPER_BURNOUT_ANALYTICS"
engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# load dataframe into PostgreSQL
table_name = "developer_burnout_data"

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'")

Data successfully loaded into table 'developer_burnout_data' in database 'DEVELOPER_BURNOUT_ANALYTICS'